### ISSUE TITLE
Script issue

### ISSUE THREAD

**Issue by yasanthachamara** [phuhl/notify-send.py#10]
Hi,

When I send a notification directly from the terminal it's working fine. But if I add it to a script, it's not appearing. If I change it to 'notify-send' it's working. Using this with deadd-notifications.
I'm using Arch with i3-gaps.

Thanks,
Yasantha

**Comment by phuhl** [comment]
Hi, what do you mean by, "if I change it to notify-send"? What did you use before?

Is your script run as root?

**Comment by phuhl** [comment]
Closed due inactivity
