### ISSUE TITLE
how to change opacity of the notification?

### ISSUE THREAD

**Issue by Aneeqasif** [phuhl/notify-send.py#22]

**Comment by phuhl** [comment]
Hi Aneeqasif, this tool does not display notifications, it sends them. The display of notifications has to be configured in the tool, that displays the notification.

Cheers

**Comment by Aneeqasif** [comment]
i am using https://github.com/phuhl/linux_notification_center sorry for inconvinience can you please guide me how to change its opacity thanks

**Comment by phuhl** [comment]
Take a look at this section of the Readme: https://github.com/phuhl/linux_notification_center#css-styling

You'll also need to have a compositor running, e.g. [picom](https://wiki.archlinux.org/title/Picom). The exact setup for your compositor depends on your distribution, you are using. Hope that helps

**Comment by Aneeqasif** [comment]
> Take a look at this section of the Readme: https://github.com/phuhl/linux_notification_center#css-styling
> 
> You'll also need to have a compositor running, e.g. [picom](https://wiki.archlinux.org/title/Picom). The exact setup for your compositor depends on your distribution, you are using. Hope that helps

yes i have tried it to and changing the css file is not causing any impact on the notification look
