### ISSUE TITLE
Actions support

### ISSUE THREAD

**Issue by resolritter** [phuhl/notify-send.py#3]
I got confused by the following image

![alt](https://raw.githubusercontent.com/phuhl/linux_notification_center/master/README.org.img/more_notifications.png)

_From [linux_notification_center](https://github.com/phuhl/linux_notification_center)_

The right-most action shows we can have buttons, but I didn't find a way to specify them, neither here or in the other repository. After running around from quite a while, I _think_ I've found the answer in [notify2's docs](https://notify2.readthedocs.io/en/latest/#notify2.Notification.add_action).

My understanding is that this is not currently implemented. Is that correct or is there an actual way of specifying the actions with the current code?

**Comment by phuhl** [comment]
New version has action support, thanks for reporting
