### ISSUE TITLE
It fails to run on Ubuntu 16.04

### ISSUE THREAD

**Issue by trappedinspacetime** [phuhl/notify-send.py#8]
Hi, 
Thank you for developing this tool.
I cloned this repository then `cd` to directory and run 

      pip install -user .`
It installed it.
When I run it

      notify-send.py -h

I get the below error

          Traceback (most recent call last):
      File "/home/****/.local/bin/notify-send.py", line 5, in <module>
        from notify_send_py.notify_send_py import main
      File "/home/****/.local/lib/python3.5/site-packages/notify_send_py/notify_send_py.py", 
    line 40
        ):
        ^
    SyntaxError: invalid syntax

**Comment by phuhl** [comment]
Hi, sorry for the late response.

Did you run it with python3? Seems to be a python version issue

**Comment by trappedinspacetime** [comment]
@phuhl Thank you for responding. I upgraded to 20.04. I don't remember if I tried it with `python3` in Ubuntu 16.04.
I close this issue.
Happy new year.

**Comment by phuhl** [comment]
All right, thanks. Happy new year's for you, too!
