### ISSUE TITLE
install fail on debian buster

### ISSUE THREAD

**Issue by ghost** [phuhl/notify-send.py#9]
git clone https://github.com/phuhl/notify-send.py
cd notify-send.py
pip install .

give this error :

Processing /home/daru/Softs/notify-send.py
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-req-build-G20v2X/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-G20v2X/

**Comment by phuhl** [comment]
Hi, thanks for reporting.

Is this still relevant? There were some major changes made, some time ago, maybe they fixed this?

**Comment by ghost** [comment]
Hi , it works fine on linux mint 20 (based on ubuntu) after completing the install with : sudo apt install libgirepository1.0-dev

But for debian buster always an error :
[screenshot error](https://paste.pics/B04MY)

**Comment by phuhl** [comment]
So, stackoverflow says, you should install setup tools: https://stackoverflow.com/questions/14426491/python-3-importerror-no-module-named-setuptools

Not sure if it has to be in the dependencies of this package (not an expert on python packages, tbh). Can you confirm that installing with setuptools installed works?

**Comment by bedax** [comment]
Hello, I am also getting the same error, with setuptools installed. I tried installing setuptools both with apt, and with pip, and the got the same result:

```
Processing /home/tom/downloads/notify-send.py
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-7k4060l1/setup.py'
```

**Comment by bedax** [comment]
Just found that this one requires `python3 -m pip install --upgrade pip` and then it works, see: https://stackoverflow.com/a/60354806

**Comment by phuhl** [comment]
Nice, thanks for the fix. I'll consider this as closed for now, if the issue reoccurs, feel free to reopen
